import { colorVariants } from '../../shared/styles';

export const layoutVariants = {
	margin: {
		spaceNone: 'm-none',
		space4XS: 'm-4xs',
		space3XS: 'm-3xs',
		space2XS: 'm-2xs',
		spaceXS: 'm-xs',
		spaceS: 'm-s',
		spaceM: 'm-m',
		spaceL: 'm-l',
		spaceXL: 'm-xl',
		space2XL: 'm-2xl',
		space3XL: 'm-3xl',
		space4XL: 'm-4xl',
		spaceAuto: 'm-auto',
	},
	marginX: {
		spaceNone: 'mx-none',
		space4XS: 'mx-4xs',
		space3XS: 'mx-3xs',
		space2XS: 'mx-2xs',
		spaceXS: 'mx-xs',
		spaceS: 'mx-s',
		spaceM: 'mx-m',
		spaceL: 'mx-l',
		spaceXL: 'mx-xl',
		space2XL: 'mx-2xl',
		space3XL: 'mx-3xl',
		space4XL: 'mx-4xl',
		spaceAuto: 'mx-auto',
	},
	marginY: {
		spaceNone: 'my-none',
		space4XS: 'my-4xs',
		space3XS: 'my-3xs',
		space2XS: 'my-2xs',
		spaceXS: 'my-xs',
		spaceS: 'my-s',
		spaceM: 'my-m',
		spaceL: 'my-l',
		spaceXL: 'my-xl',
		space2XL: 'my-2xl',
		space3XL: 'my-3xl',
		space4XL: 'my-4xl',
		spaceAuto: 'my-auto',
	},
	marginTop: {
		spaceNone: 'mt-none',
		space4XS: 'mt-4xs',
		space3XS: 'mt-3xs',
		space2XS: 'mt-2xs',
		spaceXS: 'mt-xs',
		spaceS: 'mt-s',
		spaceM: 'mt-m',
		spaceL: 'mt-l',
		spaceXL: 'mt-xl',
		space2XL: 'mt-2xl',
		space3XL: 'mt-3xl',
		space4XL: 'mt-4xl',
		spaceAuto: 'mt-auto',
	},
	marginRight: {
		spaceNone: 'mr-none',
		space4XS: 'mr-4xs',
		space3XS: 'mr-3xs',
		space2XS: 'mr-2xs',
		spaceXS: 'mr-xs',
		spaceS: 'mr-s',
		spaceM: 'mr-m',
		spaceL: 'mr-l',
		spaceXL: 'mr-xl',
		space2XL: 'mr-2xl',
		space3XL: 'mr-3xl',
		space4XL: 'mr-4xl',
		spaceAuto: 'mr-auto',
	},
	marginBottom: {
		spaceNone: 'mb-none',
		space4XS: 'mb-4xs',
		space3XS: 'mb-3xs',
		space2XS: 'mb-2xs',
		spaceXS: 'mb-xs',
		spaceS: 'mb-s',
		spaceM: 'mb-m',
		spaceL: 'mb-l',
		spaceXL: 'mb-xl',
		space2XL: 'mb-2xl',
		space3XL: 'mb-3xl',
		space4XL: 'mb-4xl',
		spaceAuto: 'mb-auto',
	},
	marginLeft: {
		spaceNone: 'ml-none',
		space4XS: 'ml-4xs',
		space3XS: 'ml-3xs',
		space2XS: 'ml-2xs',
		spaceXS: 'ml-xs',
		spaceS: 'ml-s',
		spaceM: 'ml-m',
		spaceL: 'ml-l',
		spaceXL: 'ml-xl',
		space2XL: 'ml-2xl',
		space3XL: 'ml-3xl',
		space4XL: 'ml-4xl',
		spaceAuto: 'ml-auto',
	},
	padding: {
		spaceNone: 'p-none',
		space4XS: 'p-4xs',
		space3XS: 'p-3xs',
		space2XS: 'p-2xs',
		spaceXS: 'p-xs',
		spaceS: 'p-s',
		spaceM: 'p-m',
		spaceL: 'p-l',
		spaceXL: 'p-xl',
		space2XL: 'p-2xl',
		space3XL: 'p-3xl',
		space4XL: 'p-4xl',
	},
	paddingX: {
		spaceNone: 'px-none',
		space4XS: 'px-4xs',
		space3XS: 'px-3xs',
		space2XS: 'px-2xs',
		spaceXS: 'px-xs',
		spaceS: 'px-s',
		spaceM: 'px-m',
		spaceL: 'px-l',
		spaceXL: 'px-xl',
		space2XL: 'px-2xl',
		space3XL: 'px-3xl',
		space4XL: 'px-4xl',
	},
	paddingY: {
		spaceNone: 'py-none',
		space4XS: 'py-4xs',
		space3XS: 'py-3xs',
		space2XS: 'py-2xs',
		spaceXS: 'py-xs',
		spaceS: 'py-s',
		spaceM: 'py-m',
		spaceL: 'py-l',
		spaceXL: 'py-xl',
		space2XL: 'py-2xl',
		space3XL: 'py-3xl',
		space4XL: 'py-4xl',
	},
	paddingTop: {
		spaceNone: 'pt-none',
		space4XS: 'pt-4xs',
		space3XS: 'pt-3xs',
		space2XS: 'pt-2xs',
		spaceXS: 'pt-xs',
		spaceS: 'pt-s',
		spaceM: 'pt-m',
		spaceL: 'pt-l',
		spaceXL: 'pt-xl',
		space2XL: 'pt-2xl',
		space3XL: 'pt-3xl',
		space4XL: 'pt-4xl',
	},
	paddingRight: {
		spaceNone: 'pr-none',
		space4XS: 'pr-4xs',
		space3XS: 'pr-3xs',
		space2XS: 'pr-2xs',
		spaceXS: 'pr-xs',
		spaceS: 'pr-s',
		spaceM: 'pr-m',
		spaceL: 'pr-l',
		spaceXL: 'pr-xl',
		space2XL: 'pr-2xl',
		space3XL: 'pr-3xl',
		space4XL: 'pr-4xl',
	},
	paddingBottom: {
		spaceNone: 'pb-none',
		space4XS: 'pb-4xs',
		space3XS: 'pb-3xs',
		space2XS: 'pb-2xs',
		spaceXS: 'pb-xs',
		spaceS: 'pb-s',
		spaceM: 'pb-m',
		spaceL: 'pb-l',
		spaceXL: 'pb-xl',
		space2XL: 'pb-2xl',
		space3XL: 'pb-3xl',
		space4XL: 'pb-4xl',
	},
	paddingLeft: {
		spaceNone: 'pl-none',
		space4XS: 'pl-4xs',
		space3XS: 'pl-3xs',
		space2XS: 'pl-2xs',
		spaceXS: 'pl-xs',
		spaceS: 'pl-s',
		spaceM: 'pl-m',
		spaceL: 'pl-l',
		spaceXL: 'pl-xl',
		space2XL: 'pl-2xl',
		space3XL: 'pl-3xl',
		space4XL: 'pl-4xl',
	},
} as const;

export const borderVariants = {
	borderWidth: {
		borderXS: 'border-xs',
		borderS: 'border-s',
		borderM: 'border-m',
		borderL: 'border-l',
		borderXL: 'border-xl',
	},
	borderWidthX: {
		borderXS: 'border-x-xs',
		borderS: 'border-x-s',
		borderM: 'border-x-m',
		borderL: 'border-x-l',
		borderXL: 'border-x-xl',
	},
	borderWidthY: {
		borderXS: 'border-y-xs',
		borderS: 'border-y-s',
		borderM: 'border-y-m',
		borderL: 'border-y-l',
		borderXL: 'border-y-xl',
	},
	borderWidthTop: {
		borderXS: 'border-t-xs',
		borderS: 'border-t-s',
		borderM: 'border-t-m',
		borderL: 'border-t-l',
		borderXL: 'border-t-xl',
	},
	borderWidthRight: {
		borderXS: 'border-r-xs',
		borderS: 'border-r-s',
		borderM: 'border-r-m',
		borderL: 'border-r-l',
		borderXL: 'border-r-xl',
	},
	borderWidthBottom: {
		borderXS: 'border-b-xs',
		borderS: 'border-b-s',
		borderM: 'border-b-m',
		borderL: 'border-b-l',
		borderXL: 'border-b-xl',
	},
	borderWidthLeft: {
		borderXS: 'border-l-xs',
		borderS: 'border-l-s',
		borderM: 'border-l-m',
		borderL: 'border-l-l',
		borderXL: 'border-l-xl',
	},
	radius: {
		none: 'rounded-none',
		xsmall: 'rounded-xs',
		small: 'rounded-sm',
		medium: 'rounded-md',
		large: 'rounded-lg',
		xlarge: 'rounded-xl',
		full: 'rounded-full',
	},
	borderColor: colorVariants.borderColor,
} as const;

export const visualVariants = {
	zIndex: {
		layerAuto: 'z-auto',
		layerBase: 'z-0',
		layerSticky: 'z-40',
		layerOverlay: 'z-50',
	},
	opacity: {
		opaqueNone: 'opacity-0',
		opaqueSubtle: 'opacity-25',
		opaqueMedium: 'opacity-50',
		opaqueStrong: 'opacity-75',
		opaqueFull: 'opacity-100',
	},
} as const;

export const viewVariants = {
	...layoutVariants,
	...borderVariants,
	...visualVariants,
	backgroundColor: colorVariants.backgroundColor,
} as const;

export const alignmentVariants = {
	direction: {
		row: 'flex-row',
		col: 'flex-col',
		'row-reverse': 'flex-row-reverse',
		'col-reverse': 'flex-col-reverse',
	},
	alignItems: {
		start: 'items-start',
		end: 'items-end',
		center: 'items-center',
		baseline: 'items-baseline',
		stretch: 'items-stretch',
	},
	justifyContent: {
		start: 'justify-start',
		end: 'justify-end',
		center: 'justify-center',
		between: 'justify-between',
		around: 'justify-around',
		evenly: 'justify-evenly',
	},
} as const;

export const gapVariants = {
	gap: {
		spaceNone: 'gap-none',
		space4XS: 'gap-4xs',
		space3XS: 'gap-3xs',
		space2XS: 'gap-2xs',
		spaceXS: 'gap-xs',
		spaceS: 'gap-s',
		spaceM: 'gap-m',
		spaceL: 'gap-l',
		spaceXL: 'gap-xl',
		space2XL: 'gap-2xl',
		space3XL: 'gap-3xl',
		space4XL: 'gap-4xl',
	},
	gapX: {
		spaceNone: 'gap-x-none',
		space4XS: 'gap-x-4xs',
		space3XS: 'gap-x-3xs',
		space2XS: 'gap-x-2xs',
		spaceXS: 'gap-x-xs',
		spaceS: 'gap-x-s',
		spaceM: 'gap-x-m',
		spaceL: 'gap-x-l',
		spaceXL: 'gap-x-xl',
		space2XL: 'gap-x-2xl',
		space3XL: 'gap-x-3xl',
		space4XL: 'gap-x-4xl',
	},
	gapY: {
		spaceNone: 'gap-y-none',
		space4XS: 'gap-y-4xs',
		space3XS: 'gap-y-3xs',
		space2XS: 'gap-y-2xs',
		spaceXS: 'gap-y-xs',
		spaceS: 'gap-y-s',
		spaceM: 'gap-y-m',
		spaceL: 'gap-y-l',
		spaceXL: 'gap-y-xl',
		space2XL: 'gap-y-2xl',
		space3XL: 'gap-y-3xl',
		space4XL: 'gap-y-4xl',
	},
} as const;

export function slotVariants<
	S extends string,
	V extends Record<string, Record<string, string>>,
>(
	variants: V,
	slot: S,
): { [K in keyof V]: { [VK in keyof V[K]]: Record<S, string> } } {
	type ReturnType = {
		[K in keyof V]: { [VK in keyof V[K]]: Record<S, string> };
	};
	const out = {} as ReturnType;

	for (const [key, subVariants] of Object.entries(variants)) {
		out[key as keyof V] = {} as ReturnType[keyof V];

		for (const [val, className] of Object.entries(subVariants)) {
			out[key as keyof V][val as keyof V[keyof V]] = {
				[slot]: className,
			} as Record<S, string>;
		}
	}

	return out;
}

export const flexBehaviorVariants = {
	flexGrow: {
		true: 'grow',
		nogrow: 'grow-0',
	},
	flexShrink: {
		true: 'shrink',
		noshrink: 'shrink-0',
	},
	flexWrap: {
		true: 'flex-wrap',
		nowrap: 'flex-nowrap',
		reverse: 'flex-wrap-reverse',
	},
} as const;
